CREATE OR REPLACE PACKAGE SELECTS IS
TYPE TCURSOR IS REF CURSOR;
PROCEDURE SELECT_CATEGORIA(V_CAT OUT TCURSOR);
END SELECTS;

CREATE OR REPLACE PACKAGE BODY SELECTS IS

PROCEDURE SELECT_CATEGORIA(V_CAT OUT TCURSOR)AS

BEGIN
OPEN V_CAT FOR
		SELECT * FROM CATEGORIAS;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NINGUNA CATEGORÍA');
END SELECT_CATEGORIA;
END SELECTS;

select * from categorias;
