CREATE TABLE CATEGORIAS (
    ID_CAT     NUMBER(3) CONSTRAINT CA_ID_PK PRIMARY KEY,
    NOMBRE_CAT VARCHAR2 (50) NOT NULL
);

CREATE TABLE PREGUNTAS(
    ID_PR             NUMBER(4) CONSTRAINT PR_ID_PK PRIMARY KEY,
    TEXTO_PR          VARCHAR2 (200) NOT NULL,
    ID_CAT_PR         NUMBER(3) NOT NULL, 
	CONSTRAINT PR_CA_FK FOREIGN KEY (ID_CAT_PR) REFERENCES CATEGORIAS ON DELETE CASCADE

);

CREATE TABLE RESPUESTAS(
    ID_RP           NUMBER(4) CONSTRAINT RP_ID_PK PRIMARY KEY,
    TEXTO_RP        VARCHAR2 (200) NOT NULL,
    VALOR_PR        NUMBER(1) NOT NULL,
    ID_PR_RP        NUMBER(4) NOT NULL,
	CONSTRAINT RP_PR_FK FOREIGN KEY ( ID_PR_RP ) REFERENCES PREGUNTAS ON DELETE CASCADE
);

DESC RESPUESTAS;

CREATE OR REPLACE PROCEDURE CREAR_CATEGORIA(V_NOMBRE CATEGORIAS.NOMBRE_CAT%TYPE)