CREATE OR REPLACE PACKAGE SELECTS IS
TYPE C_CURSOR IS REF CURSOR;
TYPE PR_CURSOR IS REF CURSOR;
TYPE RP_CURSOR IS REF CURSOR;

PROCEDURE SELECT_CATEGORIAS(V_CAT OUT C_CURSOR);
PROCEDURE SELECT_PREGUNTAS(V_ID_CAT IN PREGUNTAS.ID_CAT_PR%TYPE, V_PR OUT PR_CURSOR);
PROCEDURE SELECT_RESPUESTAS(V_ID_PR IN RESPUESTAS.ID_PR_RP%TYPE, V_RP OUT RP_CURSOR);

END SELECTS;


CREATE OR REPLACE PACKAGE BODY SELECTS IS
PROCEDURE SELECT_CATEGORIAS(V_CAT OUT C_CURSOR)AS
BEGIN
OPEN V_CAT FOR
		SELECT * FROM CATEGORIAS;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NINGUNA CATEGOR�A');
END SELECT_CATEGORIAS;

PROCEDURE SELECT_PREGUNTAS(V_ID_CAT IN PREGUNTAS.ID_CAT_PR%TYPE, V_PR OUT PR_CURSOR)AS
BEGIN
OPEN V_PR FOR
		SELECT * FROM PREGUNTAS WHERE ID_CAT_PR=V_ID_CAT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NINGUNA PREGUNTA');
END SELECT_PREGUNTAS;

PROCEDURE SELECT_RESPUESTAS(V_ID_PR IN RESPUESTAS.ID_PR_RP%TYPE, V_RP OUT RP_CURSOR)AS
BEGIN
OPEN V_RP FOR
		SELECT * FROM RESPUESTAS WHERE ID_PR_RP=V_ID_PR;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NINGUNA RESPUESTA');
END SELECT_RESPUESTAS;
END SELECTS;





select * from categorias;
