/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ask2gift;

import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author inaki
 */
public class PanelCatExp extends javax.swing.JPanel {

    private VExportar v = null;
    private List<Categoria> categorias;
    private Categoria categoriaSelec;
    private PanelPrExp panelprexp = null;

    /**
     * Creates new form PanelCatExp
     */
    public PanelCatExp(VExportar v, List<Categoria> categorias) {
        initComponents();
        this.v = v;
        this.categorias = categorias;

        rellenarCombo();
        selecCategoria();

    }

    public void rellenarCombo() {

        DefaultComboBoxModel modelo = new DefaultComboBoxModel();//Rellenar JComboBox
        for (Categoria cat : categorias) {
            modelo.addElement(cat.getNombre());
        }

        jComboBox1.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        selecCategoria();
        if (panelprexp != null) {
            panelprexp.rellenarUna(getCategoriaSelec());
            panelprexp.rellenarAreaPr();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed
    private void selecCategoria() {

        categoriaSelec = new Categoria();
        getCategoriaSelec().setNombre((String) jComboBox1.getSelectedItem());
        categoriaSelec = categorias.get(categorias.indexOf(getCategoriaSelec()));
        //System.out.println(categoriaSelec);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the categoriaSelec
     */
    public Categoria getCategoriaSelec() {
        return categoriaSelec;
    }

    /**
     * @param panelprexp the panelprexp to set
     */
    public void setPanelprexp(PanelPrExp panelprexp) {
        this.panelprexp = panelprexp;
    }
}
